### PR TITLE
Drop and git ignore the `pubspec.lock` for the `super_editor` library

### PR DESCRIPTION
**Pull request by domesticmouse**
Split from #292

### CODE REVIEW

**Comment by matthew-carroll** [comment]
I have the same question here. Are there things that aren't working with the current lock file? I ask because at the rate that dependencies change, we could probably churn this file every few days, but I'm not sure that would be of benefit.

**Comment by domesticmouse** [comment]
An alternative would be to remove the lock file from the repo and git ignonre it. Given you aren't after reproducible builds, having the lockfile checked in just adds noise to PRs as a file that either has to be reverted or not staged for each PR created.

**Comment by matthew-carroll** [comment]
Why do you say we're not interested in reproducible builds?

**Comment by domesticmouse** [comment]
My understanding was that reproducible builds make sense for applications, because an application build incorporates it's dependencies at the time of build. A library which is imported as a source dependency doesn't have a freeze moment. The dependency versions a library are used with is dependent on the build of the binary it itself is included in. 

This is my understanding for why the [GitHub default Dart .gitignore](https://github.com/github/gitignore/blob/master/Dart.gitignore#L7) file includes `pubspec.lock` as an ignored file, with a comment that people building applications may want to check in their lock file.

**Comment by matthew-carroll** [comment]
Ok, in that case we can get rid of the lock file for the package, but the lock file for the example app is still relevant. If people report bugs in the example app, or use the example app to reproduce bugs, then we do want a reproducible build.

**Comment by domesticmouse** [comment]
Done

**Review by matthew-carroll — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
