### PR TITLE
Cherry-pick "[SuperTextField][mobile] Update viewport height on first frame if possible (Resolves #939) (#1009)" to stable

### LINKED ISSUE #939: [SuperTextField] flicker on initial display (iOS)
In the video below we replace Text widges with `SuperTextField` upon entering edit mode. You can see that the text is missing for 1-2 frames. This does not happen on desktop.

https://user-images.githubusercontent.com/96958/212548613-c5fd706d-72eb-4aa8-86bf-14699d6927b4.mov

The culprit seems to be `TextScrollView.build`:

https://github.com/superlistapp/super_editor/blob/73990b7a72675aa730840b095e458dcde0c778f6/super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart#L466-L476

The layout is not calculated synchronously, so for several frames there is no content. But in this particular case calling `_updateViewportHeight();` directly from the build method seem to work without issues and resolves the flicker.

Is the asynchronous layout necessary? If so, can we determine cases where it's not a do it synchronously?

### PR DESCRIPTION
**Pull request by angelosilvestre**
This PR cherry-picks "[SuperTextField][mobile] Update viewport height on first frame if possible (Resolves #939) (#1009)" to stable

### CODE REVIEW

**Comment by angelosilvestre** [comment]
@matthew-carroll It seems our `ListenableBuilder` is different in the stable branch

**Comment by matthew-carroll** [comment]
@angelosilvestre can you please elaborate on what that means, and what you think we should do about it?

**Comment by angelosilvestre** [comment]
@matthew-carroll On `main`, the `ListenableBuilder` takes a `TransitionBuilder`. On `stable`, it takes a `WidgetBuilder`.

I guess we should cherry-pick https://github.com/superlistapp/super_editor/pull/880

**Comment by matthew-carroll** [comment]
That change was probably made by the Flutter team due to their `master` - does Flutter's `stable` now contain the new `ListenableBuilder`?

**Comment by angelosilvestre** [comment]
No, it doesn't seem to be on stable yet. 

That PR changes all places where we use the `ListenableBuilder`. 

I could adapt the current PR to our `ListenableBuilder` from the stable branch.

**Comment by matthew-carroll** [comment]
> I could adapt the current PR to our ListenableBuilder from the stable branch.

That's what we'll need to do. We can't do anything to our `stable` that doesn't compile against Flutter `stable`

**Review by matthew-carroll — APPROVED** [review]
LGTM

**Pull request merged**
