### PR TITLE
[SuperEditor] Fix stream leak

### PR DESCRIPTION
**Pull request by TimWhiting**
I noticed this leak of a stream controller as I was browsing the source code to get familiar with how Super Editor works.

Added a test as well.

### CODE REVIEW

**Comment by matthew-carroll** [comment]
Thanks for closing the controller. You can remove the test. The source code change seems to be an obvious requirement, and we probably don't want to write tests that check that every disposable is disposed, or closeable is closed.

**Comment by matthew-carroll** [comment]
@angelosilvestre can you check on the golden failure in this PR?

**Comment by angelosilvestre** [comment]
@matthew-carroll The same golden failed on another PR. I updated the golden in https://github.com/superlistapp/super_editor/pull/1009

It's probably a good idea to rebase this PR after https://github.com/superlistapp/super_editor/pull/1009 is merged

**Comment by matthew-carroll** [comment]
@TimWhiting can you please rebase this branch with the latest from `main`?

**Comment by TimWhiting** [comment]
Done

**Review by matthew-carroll — APPROVED** [review]
LGTM - Thanks.

@angelosilvestre please cherry pick when you get a minute.

**Pull request merged**
