### PR TITLE
[WIP] Update markdown dependency to version 6.0.0

### PR DESCRIPTION
**Pull request by dxvid-pts**
Continuation of https://github.com/superlistapp/super_editor/pull/1838

The markdown version currently in use is significantly outdated (4.0.0, released on February 11, 2021). The latest version, 7.0.0, sadly introduces many breaking changes which I didn't want to deal with since I don't want to break anything here. This PR upgrades markdown to version 6.0.0, allowing users to at least utilize a relatively newer version of flutter_markdown.

### CODE REVIEW

**Comment by matthew-carroll** [comment]
@dxvid-pts it looks like a couple of tests are failing. Can you please get those to pass again and push the changes?

**Comment by matthew-carroll** [comment]
@dxvid-pts checking in on this again. We need the tests to pass before we can consider merging this.

**Comment by dxvid-pts** [comment]
I don't fully understand yet why the tests are still failing

**Review by matthew-carroll — APPROVED** [review]
LGTM

**Comment by matthew-carroll** [comment]
@rutvik110 can you cherry pick this?

**Comment by rutvik110** [comment]
@matthew-carroll There are few tests failing for markdown deserialization with this update. Shouldn't those be fixed before we merged this change?

**Comment by matthew-carroll** [comment]
@rutvik110 I only saw golden failures. If there are Markdown failures, then yes, those should be fixed.

**Comment by rutvik110** [comment]
Goldens seems to be passing now but there are some markdown test failures seen also on `main`, we should revert this change on main for now.

**Pull request merged**
