### PR TITLE
SuperTextField: Initialize controller selection if focused during initState

### PR DESCRIPTION
**Pull request by knopp**
Partially fixes https://github.com/superlistapp/super_editor/issues/842 (for desktop platforms)

### CODE REVIEW

**Comment by matthew-carroll** [comment]
Can you describe what "partially" means? Where does this fail, and why do you think it's failing?

**Comment by knopp** [comment]
It only fixes the problem with SuperTextField on desktop. Android and iOS versions still need to be fixed. You can see the failure when you enable the test for all devices (currently is only enabled for desktop).

**Comment by matthew-carroll** [comment]
> It only fixes the problem with SuperTextField on desktop

Ok. I'd like to avoid partial solutions. Can you add the fixes for mobile? If you don't have time, would you like @angelosilvestre to take this over?

**Comment by matthew-carroll** [comment]
I'm gonna close this PR in favor of this one: https://github.com/superlistapp/super_editor/pull/846

**Pull request closed without merging**
