### PR TITLE
Fix Goldens - Option 2

### PR DESCRIPTION
**Pull request by CillianMyles**
This PR fixes the goldens by:
- Regenerating them (without any code changes) from the golden tests docker image

### CODE REVIEW

**Comment by matthew-carroll** [comment]
@CillianMyles can you let me know what the takeaway is from this PR? I don't see a description of any problems that you found or resolved - also, the goldens still fail...

**Comment by CillianMyles** [comment]
> @CillianMyles can you let me know what the takeaway is from this PR? I don't see a description of any problems that you found or resolved - also, the goldens still fail...

Apologies this one should have been removed. I assumed it would have fixed the tests by regenerating the goldens. I used a Linux/Ubuntu machine because I saw `ubuntu-latest` mentioned the GitHub actions job for the PR checks, and regenerating them on Mac failed in my PR. I did not see anything in the docs about this, or docker. I will look for info about docker and resolve the other PR.

**Comment by matthew-carroll** [comment]
@CillianMyles given that this PR gets the tests passing without altering any source code, is there any reason that we should be considering the other PR? https://github.com/superlistapp/super_editor/pull/2183

**Comment by CillianMyles** [comment]
> @CillianMyles given that this PR gets the tests passing without altering any source code, is there any reason that we should be considering the other PR? https://github.com/superlistapp/super_editor/pull/2183

If you're happier with this one then let's drop the other one. 

It's better not to change things on a whim, that are not needed, and that we don't necessarily understand the original intention behind (mixing of Android and iOS configs).

**Review by matthew-carroll — APPROVED** [review]
LGTM

**Comment by matthew-carroll** [comment]
@angelosilvestre can you cherry pick this?

**Pull request merged**
