### PR TITLE
Fix blockquote styling (Resolves #583)

### LINKED ISSUE #583: Blockquote not working properly
I ran the example app, and tried to change a paragraph to a blockquote. I expected the text to have a line on the left or some kind of border, and be able to style the text inside that blockquote.

Instead, the text loses all styles and becomes white (on a white background), and I can't change the style of any part of it.

### PR DESCRIPTION
**Pull request by angelosilvestre**
Fix blockquote styling. Resolves https://github.com/superlistapp/super_editor/issues/583

After the introduction of `Stylesheet`, blockquotes were not applying any style because `TextComponentViewModel`'s `applyStyles` was not being called.

Another issue was that `SuperEditor`'s `defaultStylesheet` was missing a default style for blockquotes, so I've added the default blockquote style that was present before 57a7d72166272582cbbdedc752b6f328c0493f88 in the `defaultStylesheet` :

https://github.com/superlistapp/super_editor/blob/a387d7f671034234eb28315f9dabc5d258bd1c33/super_editor/lib/src/default_editor/super_editor.dart#L559-L565

### CODE REVIEW

**Comment by angelosilvestre** [comment]
@matthew-carroll Could you please review this PR ?

**Review by matthew-carroll — APPROVED** [review]
LGTM - Thanks for adding tests. Can you let me know why you had to add `meta` as a dependency?

**Comment by angelosilvestre** [comment]
@matthew-carroll I've had to override the version because tests were failing in the CI due to version conflict between super_text_layout and flutter_test. (super_text_layout depends on meta version 1.8.0 and flutter_test depends on 1.7.0)

**Comment by matthew-carroll** [comment]
> super_text_layout depends on meta version 1.8.0

Looking at the change log for this PR, it looks like you're adding `meta` to `super_text_layout`...

**Comment by angelosilvestre** [comment]
My mistake. It's attributed_text that depends on meta

**Comment by matthew-carroll** [comment]
Ok. I doubt the version of `meta` matters. Can you just change `attributed_text` to use the Flutter-compatible version?

**Comment by angelosilvestre** [comment]
Done!

**Comment by matthew-carroll** [comment]
Thanks. I'll merge after CI runs.

**Comment by matthew-carroll** [comment]
@angelosilvestre it looks like the website compilation is failing. Can you take a look?

**Comment by angelosilvestre** [comment]
`Error: The getter 'SuperSelectableText' isn't defined for the class 'InsideTheToolbox'.`

This branch was still using the widgets that were renamed. I fixed that in https://github.com/superlistapp/super_editor/pull/603

I will merge main into this branch

**Comment by matthew-carroll** [comment]
Thanks. FYI - whenever possible in a PR, it's preferable to rebase `main` into your branch so that we don't accumulate a bunch of merge commits. It usually doesn't matter because we'll "squash and merge" the PR, but it's nice to get commits organized as work on top of `main`, rather than work that occasionally merges `main` into the PR branch.

**Comment by angelosilvestre** [comment]
Ok. I'll do that in the next PR's

**Pull request merged**
