### PR TITLE
Make commands atomic (Resolves #748)

### LINKED ISSUE #748: [super_editor] - Make commands atomic
While working on #736 it became apparent that notifying listeners separately for document changes and selection changes create problems when taking post processing actions.

For example, we're trying to tokenize content in paragraphs. This tokenization process depends on both the content in the paragraph, and the position of the caret. Currently, two different change notifications are fired for a single edit. The document change is fired, and the selection change is fired.

We need change notifications to fire one time per logical edit. Also, we generally need to clean up the command system because we have edits that are firing multiple commands for a single operation, and some of those handlers are inspecting information in between the commands. This isn't how commands are supposed to work.

A possible approach:

- Calculate all necessary information in a handler before running any commands
- Batch all relevant commands into a `BatchCommand`, and then execute it
- Create a unified listener system and invoke the unified notification after the command or batch command is done

### PR DESCRIPTION
**Pull request by matthew-carroll**
This PR converts all existing document editing and selection change behavior to use a request/command/event triad.

A desired outcome begins with a "request".

Each "request" is passed down a chain of responsibility to find a compatible "command".

The first compatible "command" is executed, which changes the underlying document. One "command" might cause other "commands" to run. Each "command" accumulates "change events" as it mutates the document. Those "change events" are saved, in-order, until all commands are finished. Then, all of those "change events" are sent to document listeners as a "change log".

The reason that "requests" are separated from "commands" is because "commands" include implementation details for document alteration. For example, a "command" would know about a database that holds document information. As a result, the same request, such as "delete selected text", might be handled by different "commands", based on the specific implementation of the document.

### CODE REVIEW

**Comment by matthew-carroll** [comment]
@miguelcmedeiros @roughike - Here's a first draft of the atomic command changes. I probably could have continued to massage the API, but I think it would be more effective to have you guys try to start integrating the API and see what makes sense and what doesn't. We can do some pair-programming, if that would help.

**Comment by matthew-carroll** [comment]
@Jethro87 - FYI, you'll want to at least be aware of this PR. It's a foundational change to Super Editor, which is needed for undo/redo support, as well as concurrent editing support. Feel free to provide any opinions on the API.

@venkatd - I know you're working on other things these days, but just in case you're curious, this PR is the beginning of Super Editor's transition to undo/redo.

**Comment by matthew-carroll** [comment]
@angelosilvestre - CC for visibility. No review needed, but this PR will change a large swathe of the codebase. Feel free to ask any questions.

**Comment by zaynetro** [comment]
This is an excellent feature!

One thing that would be nice to have is the ability to inspect and alter the transaction changes before committing. Use case: disallow deleting certain nodes, like unselectable HR or an image.

Sorry, for if this isn't the right place or time for requests :/

**Comment by matthew-carroll** [comment]
@zaynetro - That's a reasonable request. Once these changes are merged, I would recommend trying them for your use-case and if they don't do what you need, then file an issue describing what you're looking for. This API will likely evolve quite a bit. In fact, it's still evolving in this PR, which is why it hasn't been merged yet.

**Comment by raulmabe-labhouse** [comment]
Hi 👋🏼  How is the state of this PR? I assume its low priority as its been inactive for very long. Do you have any insights on when will be merged?

**Comment by miguelcmedeiros** [comment]
@matthew-carroll I guess we can close this one.

**Pull request closed without merging**
