### PR TITLE
Don't delete content when control keys are pressed with a selection (Resolves #1331)

### LINKED ISSUE #1331: [SuperEditor] - Tab key deletes content
Reproduction: select some text, press TAB.

Expected: focus moves and content remains unchanged.

Actual: focus moves, selected content is deleted.

We need to adjust the keyboard handlers to keep non-content keys from deleting content.

### PR DESCRIPTION
**Pull request by matthew-carroll**
Don't delete content when control keys are pressed with a selection (Resolves #1331)

### CODE REVIEW

**Comment by rutvik110** [comment]
I'm not able to reproduce the issue this PR solves on my side on `main`?

**Comment by rutvik110** [comment]
Now that I remember, I believe we address an similar issue earlier in this (https://github.com/superlistapp/super_editor/pull/1286) PR where pressing control keys would insert an `?` character while deleting the selected content.  I believe that's why I'm not able to reproduce this issue now.

**Review by rutvik110 — APPROVED** [review]
LGTM!

**Comment by angelosilvestre** [comment]
After https://github.com/superlistapp/super_editor/pull/1339 is merged, we need to make sure this handler is placed after the short-circuit handler, to let the IME handle these keys.

**Comment by matthew-carroll** [comment]
@angelosilvestre You can make that change, right? If I merge this in then you can rebase?

**Comment by matthew-carroll** [comment]
Actually, @angelosilvestre, this handler is already merged in isn't it? I only changed what it filters. Either way, I'll merge this and you can update as needed.

**Review by angelosilvestre — COMMENTED** [review]
LGTM

**Pull request merged**
