### PR TITLE
Adding flutter_lints

### PR DESCRIPTION
**Pull request by domesticmouse**
Hey @matthew-carroll,

I tried adding [flutter_lints](https://pub.dev/packages/flutter_lints), but the tests are failing. However, the reason is unmigrated code in the spikes directory, so I'm unsure what you want to do about that.

brett

### CODE REVIEW

**Comment by matthew-carroll** [comment]
I'll look through this. It's probably time to delete the spikes.

One thing I'm noticing is a possible line-length difference. I have mine set to 120 in the IDE. Do you know if there's a way to set that in the lint rules? I think 80 is too short.

**Comment by domesticmouse** [comment]
I'll reformat for 120

**Comment by domesticmouse** [comment]
Looks like configuring Dartfmt's line length is a non-starter: https://github.com/dart-lang/dart_style/issues/918

I'd suggest adding a check to your Github Actions that checks if a dart format with line length of 120 changes things. Happy to add it to this PR if ya want.

**Comment by matthew-carroll** [comment]
> I'd suggest adding a check to your Github Actions that checks if a dart format with line length of 120 changes things. Happy to add it to this PR if ya want.

Sure, if you know where/how to add that then I'd say go for it. Thanks.

**Comment by domesticmouse** [comment]
Pulled the 120 char line length change into a separate PR: https://github.com/superlistapp/super_editor/pull/229

**Comment by matthew-carroll** [comment]
@domesticmouse it looks like a number of tests broke with this PR. Any idea why?

**Comment by domesticmouse** [comment]
Nope. I don't know what the failing tests are. They don't look like GitHub Action CI failures.

**Comment by domesticmouse** [comment]
Looks like I `const`ified lists that shouldn't have been `const`ed. I'll re-run locally and debug.

**Comment by domesticmouse** [comment]
Tests now pass locally. Hopefully it should also pass in CI.

**Comment by domesticmouse** [comment]
Non-netlify tests pass. No idea why the netlify tests are failing. 

Halp?

**Comment by matthew-carroll** [comment]
The website build failures are unrelated to this, we can ignore them. I'll merge this in.

**Review by matthew-carroll — APPROVED** [review]

**Pull request merged**
