### PR TITLE
Add a dart format check for 120 char line length

### PR DESCRIPTION
**Pull request by domesticmouse**
In theory, this check should fail as there are two dart files that `dart format` will want to change. I'll update them in this PR, once we have confirmed Github Action sets a failure flag.

### CODE REVIEW

**Review by matthew-carroll — APPROVED** [review]
LGTM

**Comment by matthew-carroll** [comment]
@domesticmouse it looks like the new validation check found some format changes and failed.

**Comment by domesticmouse** [comment]
Well, at least the line length check passes now...

**Comment by matthew-carroll** [comment]
I'm going to submit this with CI failures because the failures are related to out-of-date website code.

I filed: https://github.com/superlistapp/super_editor/issues/240

**Pull request merged**
