### PR TITLE
Paragraph alignment now changes immediately - moved paragraph change from direct document manipulation to a request/command pair (Resolves #1587)

### LINKED ISSUE #1587: Changing text alignment doesn't reflect the alignment change on the text node within the document immediately.
**The Issue:**

Changing text alignment of a paragraph node doesn't reflect the alignment change immediately in the document. This change is reflected only after I make any other edits to the document.

To reproduce: 

1. Select any text within `SuperEditor`.
2. Change text alignment through alignment dropdown within toolbar.
3. Make any arbitrary edits to the document to see the text alignment change.

Demo:

https://github.com/superlistapp/super_editor/assets/65209850/47c44e02-5988-4922-a3e5-17f3c1eeb780

**Expected behaviour:**

Change in text alignment should be reflected immediately in the document.

### PR DESCRIPTION
**Pull request by matthew-carroll**
Paragraph alignment now changes immediately - moved paragraph change from direct document manipulation to a request/command pair (Resolves #1587)

https://github.com/superlistapp/super_editor/assets/7259036/fb46e49a-6c91-4ba4-ad9e-11cf8619ec60

### CODE REVIEW

**Comment by matthew-carroll** [comment]
@rutvik110 here's a tactical change that appears to resolve the alignment delay issue. This approach doesn't touch any render objects, or even touch any widgets. Everything happens within the standard `SuperEditor` pipeline. Here's how I approached this problem.

1. Locate the toolbar where paragraph alignment is controlled. I noticed that the toolbar was directly mutating the document, which is something that should never happen in `SuperEditor` any more. Everything should go through requests and commands.
2. I took the existing direct mutation approach from the toolbar and wrote a failing test that shows that after a pump the widget alignment doesn't change.
3. Opened the existing paragraph file and found that we already had a request/command pair that changes the block type. This pair was almost identical to what we needed for paragraph alignment. I copied this pair and adjusted for alignment.
4. I switched the toolbar to use the new request/command pair and the demo app worked fine.
5. I switched the test to use the request/command pair and the test passed.

By starting from the perspective of how alignment should be controlled in `SuperEditor`, rather than focusing on low level Flutter framework details, it was very quick and easy to solve this. When working on future issues, please try working in a similar direction, and by taking similar steps. Ask questions along the way if you can't find something.

**Comment by rutvik110** [comment]
Followed the same approach in the closed PR and it does solves the issue of changing alignment immediately but the text cursor still doesn't get updated immediately wrt new text alignment. The change that I was proposing earlier was related to fixing this particular issue. 

https://github.com/superlistapp/super_editor/assets/65209850/9cf413f7-b2f5-4a3e-8a8c-30bacee7ae5c

**Comment by matthew-carroll** [comment]
Ok, I'll follow up to investigate the caret placement. Thanks for letting me know.

**Comment by matthew-carroll** [comment]
@rutvik110 I traced the various build and layout calls until I eventually discovered that Flutter's `RenderParagraph` setter for `textAlign` was only calling `markNeedsPaint()` instead of `markNeedsLayout()`. This means that when the text alignment changes, Flutter doesn't think any layout details changed, which prevents ancestors from running their own layout again.

I overrode the default setter and added a `markNeedsLayout()` call. I also filed https://github.com/flutter/flutter/issues/140756.

Was this the same path you were on in your PR?

**Comment by rutvik110** [comment]
> Was this the same path you were on in your PR?

yah, the same one.

**Comment by matthew-carroll** [comment]
@rutvik110 can you do a review?

**Review by rutvik110 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
