### PR TITLE
Reformat example for line length of 120

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Comment by matthew-carroll** [comment]
I have the same question here as before. Isn't there already a VSCode line length format configuration file? Is it not applying to the example sub-project?

**Comment by matthew-carroll** [comment]
I see you answered the question about the settings file in the other PR. Can you remove the attributions format change in this PR?

**Comment by domesticmouse** [comment]
> Can you remove the attributions format change in this PR?

Done

**Review by matthew-carroll — APPROVED** [review]
LGTM

**Pull request merged**
