### PR TITLE
Create mobile text fields for Android and iOS

### PR DESCRIPTION
**Pull request by matthew-carroll**
Introduces `SuperAndroidTextField` and `SuperIOSTextField`, which use Flutter's new delta reporting system to bring IME input to super_editor's custom text fields.

The desktop `SuperTextField` remains as-is for now. In fact, the delta system is not yet implemented for non-mobile platforms.

The goal of this PR is to implement a big chunk of mobile text fields to the point that they are usable for some use-cases in production. I'm sure that this PR includes bugs in the text fields. There is also a lack of per-platform visual styling around the text fields, e.g., the underline on Material text fields. If the bugs are minor enough that these text fields can be used in production, then we should merge this PR and continue from there. If the bugs are too severe, then we should solve them in this PR.

There are some conflicts in this PR. I'll resolve those whenever the work in this PR is ready to merge.

Here are some videos of the mobile text fields. I had to record both text field implementation in an Android emulator because the iOS simulator software keyboard seems to be broken right now for Flutter apps.

**Android**

https://user-images.githubusercontent.com/7259036/134473728-c691b963-4fb2-4622-a30a-ab224fc0d08c.mov

**iOS**

https://user-images.githubusercontent.com/7259036/134473758-03d3ea9d-ad4f-4add-b423-acac5e8b66c5.mov

### CODE REVIEW

**Comment by matthew-carroll** [comment]
CC @venkatd @Jethro87

**Comment by venkatd** [comment]
@matthew-carroll  this is great!

Once this is merged in, I'd be happy to investigate deltas on the web side.

One point of clarification: what is the relation between the SuperAndroidTextField/SuperIOSTextField and SuperEditor? Are these closer to SuperTextField than they are to SuperEditor?

**Comment by matthew-carroll** [comment]
@venkatd The new text fields have no relationships to `SuperEditor`. They're just text fields. However, some similar work will need to be done to `SuperEditor` to support mobile.

**Comment by Jethro87** [comment]
These look great, @matthew-carroll! Personally, the platform-specific visual styling issues (i.e., underlining on Android) aren't likely to be a blocker for us re: merging this PR and moving forward.

**Comment by matthew-carroll** [comment]
Thanks @Jethro87 - do you wanna try one or two integrations of the work in this PR within your app? I think it would be a good idea to stress test these text fields as much as we can before merging them in.

**Comment by matthew-carroll** [comment]
@venkatd @Jethro87 - Did either of you get a chance to try these text fields?

**Comment by Jethro87** [comment]
@matthew-carroll I took a long weekend and will be back tomorrow (haven't tried the text fields yet). I should be able to try it out in the next day or two.

**Comment by Jethro87** [comment]
@matthew-carroll I played with `SuperIOSTextField` on a physical iOS device today. Generally, the field works well and I'm encouraged by the progress. Styling the text felt great. This wouldn't be ready for production as of yet in my opinion, though, as there were several issues that made the experience feel a bit rough.

Here's a few of the issues I found:

### Cut/Copy/Paste menu overflows the side of the screen

EEE8221B-EBEE-420E-89EC-704328661F97_1_201_a

### Selector doesn't move with the bounds of the highlighted text when styling it
This happened when bolding "SuperiOSTextField" then unbolding it.

CE358A58-DE6A-4D89-9EB4-19CF27A99F09_1_201_a

### Loupe moves outside of text field when trying to scroll the field

D29799DD-7F35-4BDB-B6D1-756A482D6597_1_201_a

### Dragging the loupe outside of the text field and to the extreme bottom of the device causes the text field content to continuously "jump"

FD46491C-54B3-4D06-9E85-3E6041867185_2_0_a

### Selecting text and dragging one of the selectors vertically out of the bounds of the text field doesn't scroll the field as it should

E7100848-0D2E-4336-A69E-90B1387DF9B7_1_105_c

**Comment by matthew-carroll** [comment]
Thanks for the feedback with videos. I'll take a look into those issues and see if I can get them fixed.

**Comment by matthew-carroll** [comment]
@Jethro87 I think I've solved everything you mentioned except for the magnifier moving outside the field. Can you verify the fixes on your end?

For the magnifier, do you have a video for what the behavior should be when dragging beyond the bounds of the field? The magnifier circle definitely needs to exceed the bounds of the field when you drag near the edges. I don't know what's supposed to happen when you drag completely outside the field.

**Comment by Jethro87** [comment]
@matthew-carroll I can confirm that the issues have been solved. Regarding:

> For the magnifier, do you have a video for what the behavior should be when dragging beyond the bounds of the field? The magnifier circle definitely needs to exceed the bounds of the field when you drag near the edges. I don't know what's supposed to happen when you drag completely outside the field.

it appears that what you've done mirrors the iOS default behavior. Here's a quick video of how it works in Apple Notes. for reference:

https://user-images.githubusercontent.com/6467808/136133436-784b98cc-cc94-425b-8a9f-6b5f79b64e70.mp4

I found another couple of issues while testing tonight:

### Without selecting any text, try to "Cut" in an empty space. The following error occurs in file `super_textfield`:

`_AssertionError ('package:super_editor/src/infrastructure/super_textfield/super_textfield.dart': Failed assertion: line 2294 pos 12: '!selection.isCollapsed': is not true.)`

### There is no acceleration on the text field when scrolling the loupe vertically outside of the text field 

In Apple Notes app, I noticed that the scrolling accelerates the further down I pull the loupe. This isn't a big issue right now.

**Comment by matthew-carroll** [comment]
@Jethro87 I'll address the "cut" bug and the magnifier UI.

Do you think we can move forward without the scrolling acceleration?

**Pull request merged**
