### PR TITLE
Replace textScaleFactor with TextScaler (Resolves #1238)

### LINKED ISSUE #1238: Replace `textScaleFactor` with `TextScaler` on main
On Flutter's latest main, `textScaleFactor` is deprecated in favor of `TextScaler`.

Because of that, the CI is failing for `super_text_layout`: 

```
Analyzing super_text_layout...                                  

   info • 'textScaleFactorOf' is deprecated and shouldn't be used. Use textScalerOf instead. Use of textScaleFactor was deprecated in preparation for the upcoming nonlinear text scaling support. This feature was deprecated after v3.12.0-2.0.pre • lib/src/super_text.dart:96:63 • deprecated_member_use
   info • 'textScaleFactor' is deprecated and shouldn't be used. Use textScaler instead. Use of textScaleFactor was deprecated in preparation for the upcoming nonlinear text scaling support. This feature was deprecated after v3.12.0-2.0.pre • lib/src/super_text.dart:307:11 • deprecated_member_use
   info • 'textScaleFactor' is deprecated and shouldn't be used. Use textScaler instead. Use of textScaleFactor was deprecated in preparation for the upcoming nonlinear text scaling support. This feature was deprecated after v3.12.0-2.0.pre • lib/src/super_text.dart:323:24 • deprecated_member_use
   info • 'textScaleFactor' is deprecated and shouldn't be used. Use textScaler instead. Use of textScaleFactor was deprecated in preparation for the upcoming nonlinear text scaling support. This feature was deprecated after v3.12.0-2.0.pre • lib/src/super_text.dart:342:9 • deprecated_member_use
   info • 'textScaleFactor' is deprecated and shouldn't be used. Use textScaler instead. Use of textScaleFactor was deprecated in preparation for the upcoming nonlinear text scaling support. This feature was deprecated after v3.12.0-2.0.pre • lib/src/super_text.dart:342:27 • deprecated_member_use
   info • 'textScaleFactor' is deprecated and shouldn't be used. Use textScaler instead. Use of textScaleFactor was deprecated in preparation for the upcoming nonlinear text scaling support. This feature was deprecated after v3.12.0-2.0.pre • lib/src/super_text.dart:377:11 • deprecated_member_use
   info • 'textScaleFactor' is deprecated and shouldn't be used. Use textScaler instead. Use of textScaleFactor was deprecated in preparation for the upcoming nonlinear text scaling support. This feature was deprecated after v3.12.0-2.0.pre • lib/src/super_text_inspector.dart:29:3[8](https://github.com/superlistapp/super_editor/actions/runs/5592967005/jobs/10226095318?pr=1234#step:5:9) • deprecated_member_use
   info • 'textScaleFactorOf' is deprecated and shouldn't be used. Use textScalerOf instead. Use of textScaleFactor was deprecated in preparation for the upcoming nonlinear text scaling support. This feature was deprecated after v3.12.0-2.0.pre • lib/src/super_text_layout_with_selection.dart:[11](https://github.com/superlistapp/super_editor/actions/runs/5592967005/jobs/10226095318?pr=1234#step:5:12)1:61 • deprecated_member_use
   info • 'textScaleFactor' is deprecated and shouldn't be used. Use textScaler instead. Use of textScaleFactor was deprecated in preparation for the upcoming nonlinear text scaling support. This feature was deprecated after v3.[12](https://github.com/superlistapp/super_editor/actions/runs/5592967005/jobs/10226095318?pr=1234#step:5:13).0-2.0.pre • lib/src/text_layout.dart:200:50 • deprecated_member_use
```

Replace `textScaleFactor` and `textScaleFactor` usages with `TextScaler`.

Reference: https://github.com/flutter/flutter/pull/128522

### PR DESCRIPTION
**Pull request by knopp**
Fixes https://github.com/superlistapp/super_editor/issues/1238

### CODE REVIEW

**Comment by knopp** [comment]
I don't know how to make the PR check pass given that it builds against a published package and thus it does not compile. How do you address this on CI without melos?

**Comment by angelosilvestre** [comment]
Usually, overriding the dependency in pubspec.yaml to use the path dependency is enough.

**Comment by knopp** [comment]
I do that locally, but what about the PR?

**Comment by angelosilvestre** [comment]
I guess we'll need to release a new version of super_text_layout.

**Comment by matthew-carroll** [comment]
@knopp can you rebase against `main`?

**Comment by matthew-carroll** [comment]
I put up https://github.com/superlistapp/super_editor/pull/1252 with the latest from `main` so that I can merge it in.

**Pull request closed without merging**
