### PR TITLE
204: Fix the selection problem on null safe projects.

### LINKED ISSUE #204: [BUG] NodeSelection problem on migrated Null Safe projects
Steps to Reproduce
- Run the editor on a null safe app (you can migrate the main example app as well for trying)
- Run the application
Expected
- App shows the editor
Actual
- App gives the following error
```
type 'Null' is not a subtype of type 'TextSelection' in type cast
```

### PR DESCRIPTION
**Pull request by salihgueler**
Fixes #204

### CODE REVIEW

**Comment by matthew-carroll** [comment]
I don't think this should ever be `null`. Can you describe where this is an issue?

**Comment by salihgueler** [comment]
> I don't think this should ever be `null`. Can you describe where this is an issue?

With any null safe app, this issue happens. For reproducing you can migrate example app with 'dart migrate --skip-import-check' and run the app.

**Comment by matthew-carroll** [comment]
What's the actual error and where are you seeing it?

**Comment by salihgueler** [comment]
> What's the actual error and where are you seeing it?

The error is as described in the Github issue #204. It points to the parts that I made the change. 

Basically error says, you are trying to assign null to TextSelection

**Comment by matthew-carroll** [comment]
Ok, I've reproduced the issue. After some initial investigation it still looks like the property should not be nullable, so this change is not the appropriate fix. I'll put up a PR for this later tonight.

In the future, if you could post the stacktrace that would be helpful. This issue could probably have been debugged with just a stacktrace instead of a project migration and deployment.

**Comment by matthew-carroll** [comment]
Taking a 2nd look at this PR, I thought the `?` was being applied to the node's selection rather than the builder's selection. I think this change might be correct after all. I'm going to take one more look and then merge this if it looks like it covers all the component builders.

**Comment by matthew-carroll** [comment]
Ok, I thought maybe this was missing the `ParagraphBuilder` but I see that this condition was already taken into account in that component builder. I'm going to approve this and merge it. I'm also going to put up a PR that migrates the example app to null safety.

**Review by matthew-carroll — APPROVED** [review]

**Pull request merged**
