### PR TITLE
Fix layout exception with shrinkwrap

### PR DESCRIPTION
**Pull request by knopp**
Needs test

### CODE REVIEW

**Comment by matthew-carroll** [comment]
Please ping me when you've added the test.

**Comment by matthew-carroll** [comment]
@knopp can we get some tests added to this?

**Comment by knopp** [comment]
@matthew-carroll, sorry for the delay, added test.

**Review by matthew-carroll — APPROVED** [review]
LGTM

**Comment by matthew-carroll** [comment]
@angelosilvestre can you cherry pick this?

**Pull request merged**
