### PR TITLE
Store a copy of attributions provided to AttributedSpans

### PR DESCRIPTION
**Pull request by britannio**
Closes https://github.com/superlistapp/super_editor/issues/260

| Before                                                                                                                                                                 | After                                                                                                                                                                  |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Screenshot 2021-06-26 at 23 31 26 | Screenshot 2021-06-26 at 23 47 03 |

### CODE REVIEW

**Comment by britannio** [comment]
Hey @matthew-carroll, this fix is a one liner so it should be a quick review. I also proposed an alternative solution in #260 if that's preferred.

**Comment by matthew-carroll** [comment]
Thanks for filing the issue and the PR. I checked #227 that you referenced, but I don't see where the spans were changed to `const` in that PR. It also looks like the existing code that's being changed in this PR reads `attributions ?? []`, which should instantiate a non-`const` list when no attributions are provided.

Is the goal here to prevent clients from passing in a `const` list?

**Comment by britannio** [comment]
The `const` keyword causing the issue is at [_interactive_demo.dart](https://github.com/superlistapp/super_editor/pull/227/files#diff-ceaa52a1e5d0b4522dfea9341c26f3cb916b59c2250b931a11e2828b8e8b43c0R17).

> Is the goal here to prevent clients from passing in a const list?

The goal is to allow clients to pass const and mutable lists without anything breaking. At the moment, `AttributedSpans` only supports mutable lists.

**Review by matthew-carroll — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
